CREATE TABLE student (id SERIAL PRIMARY KEY, school_id INT, username VARCHAR(40) UNIQUE, password VARCHAR(70), email VARCHAR(40), avatar TEXT);
CREATE TABLE students (student_id INT, lesson_id INT PRIMARY KEY);
CREATE TABLE lesson (name VARCHAR(50), lessondescription TEXT, id SERIAL PRIMARY KEY);
CREATE TABLE teacher (id SERIAL PRIMARY KEY, school_id INT, username VARCHAR(40) UNIQUE, password VARCHAR(70), email VARCHAR(40), avatar TEXT);
CREATE TABLE teachers (teacher_id INT, lesson_id INT PRIMARY KEY);
CREATE TABLE homework (id SERIAL  PRIMARY KEY, teachers_id INT , students_id INT , description TEXT );
CREATE TABLE school (id SERIAL, school_name VARCHAR(100) PRIMARY KEY, username VARCHAR(40), password VARCHAR(70));
CREATE TABLE timetable (id SERIAL PRIMARY KEY, lesson_id INT);
CREATE TABLE time (timetable_id INT, time VARCHAR(75));
CREATE TABLE email (id SERIAL PRIMARY KEY, text TEXT, title TEXT);
CREATE TABLE emails (user_id INT, email_id INT PRIMARY KEY);